import type { AgentStore } from "../types.js";
import { generateOrchestrationPlan } from "../nexus.js";

export function orchestrate(
  store: AgentStore,
  options: {
    task: string;
    mode: "micro" | "sprint" | "full";
    constraints?: string;
  }
): string {
  const { task, mode, constraints = "" } = options;

  const plan = generateOrchestrationPlan(store, task, mode, constraints);

  const lines: string[] = [];

  lines.push(`# NEXUS Orchestration Plan`);
  lines.push("");
  lines.push(`**Task**: ${task}`);
  lines.push(`**Mode**: ${mode.toUpperCase()}`);
  lines.push(`**Total Agents**: ${plan.total_agents}`);
  lines.push(`**Phases**: ${plan.estimated_phases}`);
  if (constraints) {
    lines.push(`**Constraints**: ${constraints}`);
  }
  lines.push("");
  lines.push("---");

  for (const phase of plan.phases) {
    lines.push("");
    lines.push(
      `## Phase ${phase.phase_id}: ${phase.phase_name}`
    );
    lines.push(`> ${phase.objective}`);
    lines.push("");

    if (phase.agents.length > 0) {
      lines.push("### Active Agents");
      for (const agent of phase.agents) {
        lines.push(`- **${agent.name}** (\`${agent.slug}\`) — ${agent.primaryOutput}`);
      }
    } else {
      lines.push("### Active Agents");
      lines.push("- No agents activated for this phase in current mode.");
    }

    if (phase.parallel_tracks.length > 0) {
      lines.push("");
      lines.push("### Parallel Workstreams");
      let trackLabel = "A";
      for (const track of phase.parallel_tracks) {
        lines.push(`**Track ${trackLabel}**: ${track.join(", ")}`);
        trackLabel = String.fromCharCode(trackLabel.charCodeAt(0) + 1);
      }
    }

    lines.push("");
    lines.push(
      `### Quality Gate — Gate Keepers: **${phase.quality_gate.gate_keepers.join(
        "**, **"
      )}**`
    );
    for (const criterion of phase.quality_gate.criteria) {
      lines.push(`- ${criterion.criterion}: ${criterion.threshold}`);
    }

    lines.push("");
    lines.push(`### Handoff`);
    lines.push(phase.handoff);
    lines.push("");
    lines.push("---");
  }

  lines.push("");
  lines.push("## Activation Instructions");
  lines.push("1. Start at Phase 0 and progress sequentially through all phases.");
  lines.push(
    `2. For each agent listed, use \`invoke_agent\` with the agent slug and a description of their task for the current phase.`
  );
  lines.push(
    "3. Do NOT advance to the next phase until the current phase's quality gate criteria are met."
  );
  lines.push("4. Use parallel workstreams within a phase to compress timelines.");
  lines.push(
    "5. If a task fails QA more than 3 times, escalate to the phase's Gate Keeper for resolution."
  );
  lines.push("");
  lines.push(
    `> Generated by Agency MCP Server NEXUS Engine | Mode: ${mode.toUpperCase()} | Agents: ${plan.total_agents}`
  );

  return lines.join("\n");
}
